---
- name: Setting make_user.sql
  shell: "/{{ user }}/automation/db_files/gen_makeusersql.sh"
          
- name: Create iaas db user
  shell: "tbsql sys/tibero @/{{ user }}/automation/db_files/sql_script/make_user.sql"

- name: Execute iaas table sql
  shell: "tbsql {{ tid }}/{{ tpw }} @/{{ user }}/automation/db_files/sql_script/create_table.sql"

- name: Execute volume manager sql
  shell: "tbsql {{ tid }}/{{ tpw }} @/{{ user }}/automation/db_files/sql_script/csvmgr_schema.sql"
