DROP TABLE "ACTIONINFO";
DROP TABLE "AUTOSCALEINFO";
DROP TABLE "COMPUTENODEINFO";
DROP TABLE "DBINFO";
DROP TABLE "FILESTORAGEINFO";
DROP TABLE "FILESTORAGEMAPPING";
DROP TABLE "GROUPEXECUTEINFO";
DROP TABLE "GROUPINFO";
DROP TABLE "HOSTINFO";
DROP TABLE "HOSTSHAREINSTANCEMAPPINGINFO";
DROP TABLE "IMAGE";
DROP TABLE "IMAGELAYERMAPPED";
DROP TABLE "INNERFILESYSTEMINFO";
DROP TABLE "INSTANCEINFO";
DROP TABLE "INSTANCESPECINFO";
DROP TABLE "LAYER";
DROP TABLE "NODEIMAGE";
DROP TABLE "PACKINFO";
DROP TABLE "PHYSICALIMAGE";
DROP TABLE "SERVICEINFO";
DROP TABLE "STORAGEGROUPINFO";
DROP TABLE "STORAGENODEINFO";
DROP TABLE "STORAGESERVERGROUPINFO";
DROP TABLE "STORAGESERVERINFO";
DROP TABLE "STORAGEUNITINFO";

CREATE TABLE "IMPADMIN"."ACTIONINFO" (
	"ACTIONID" NUMBER(15),
	"GROUPID" NUMBER(15),
	"ACTIONTYPE" NUMBER(1),
	"CONTENTTYPE" VARCHAR(25),
	"CONTENT" VARCHAR(1000)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."AUTOSCALEINFO" (
	"AUTOSCALEID" NUMBER,
	"MIN" NUMBER,
	"MAX" NUMBER,
	"OUTEVENTID" NUMBER,
	"OUTPOLICY" VARCHAR(255),
	"OUTCOOLDOWN" NUMBER,
	"INEVENTID" NUMBER,
	"INPOLICY" VARCHAR(255),
	"INCOOLDOWN" NUMBER,
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"RECENTINEVENT" TIMESTAMP,
	"RECENTOUTEVENT" TIMESTAMP,
	"AUTOCOUNT" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."COMPUTENODEINFO" (
	"COMPUTENODEID" NUMBER,
	"HOSTID" NUMBER,
	"TOTALCPU" NUMBER(9),
	"FREECPU" NUMBER(9),
	"TOTALMEMORY" NUMBER(9),
	"FREEMEMORY" NUMBER(9),
	"TOTALDISK" NUMBER(9),
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"ACCESSNAME" VARCHAR(255),
	"ACCESSAUTH" VARCHAR(2048),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."DBINFO" (
	"DBID" NUMBER,
	"STORAGESERVERGROUPID" NUMBER,
	"DBINSTANCEID" NUMBER,
	"TOTALSIZE" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."FILESTORAGEINFO" (
	"FILESTORAGEID" NUMBER,
	"STORAGEUNITID" NUMBER,
	"STORAGEGROUPID" NUMBER,
	"TOTALSIZE" NUMBER(9),
	"FREESIZE" NUMBER(9),
	"ISRW" NUMBER(1),
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"CDSLOGINUSERID" VARCHAR(255),
	"CDSLOGINUSERPW" VARCHAR(255),
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."FILESTORAGEMAPPING" (
	"INSTANCEID" NUMBER,
	"FILESTORAGEID" NUMBER,
	"INSTANCEMOUNTPATH" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."GROUPEXECUTEINFO" (
	"GROUPID" NUMBER(15),
	"SVCORDER" NUMBER(5),
	"SVCNAME" VARCHAR(100),
	"SVCUUID" VARCHAR(15)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."GROUPINFO" (
	"GROUPID" NUMBER(19),
	"CREATEDTIME" TIMESTAMP,
	"GROUPDESCRIPTION" VARCHAR(255),
	"GROUPNAME" VARCHAR(255),
	"GROUPTAGS" VARCHAR(255),
	"PROJECTUUID" NUMBER(19),
	"SCRIPT" VARCHAR(10000),
	"STATUS" VARCHAR(255),
	"TENANTUUID" NUMBER(19),
	"UPDATEDTIME" TIMESTAMP,
	"CREATOR" VARCHAR(255),
	"INSTANCECOUNT" NUMBER(10),
	"PACKNAME" VARCHAR(255),
	"PROJECTID" NUMBER(19),
	"TENANTID" NUMBER(19)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."HOSTINFO" (
	"HOSTID" NUMBER,
	"HOSTNAME" VARCHAR(255),
	"HOSTTYPE" VARCHAR(255),
	"HYPERVISORTYPE" VARCHAR(255),
	"HOSTIP" VARCHAR(255),
	"CPUARCH" VARCHAR(255),
	"TOTALCPU" NUMBER,
	"TOTALMEMORY" NUMBER,
	"TOTALDISK" NUMBER,
	"AVAILABILITYZONE" VARCHAR(255),
	"STATUS" VARCHAR(255),
	"HOSTPMAC" VARCHAR(255),
	"EXTERNALPORT" VARCHAR(255),
	"INTERNALPORT" VARCHAR(255),
	"SWITCHDPID" NUMBER,
	"SWITCHPORT" NUMBER,
	"ACTIVE" NUMBER,
	"HOSTAGENTNUM" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"ACCESSNAME" VARCHAR(255),
	"ACCESSAUTH" VARCHAR(2048),
	"POOLEDDISK" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."HOSTSHAREINSTANCEMAPPINGINFO" (
	"HOSTSHAREINSTANCEMAPPINGID" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"HOSTPATH" VARCHAR(255),
	"HOSTSHAREINSTANCEMAPPINGUUID" VARCHAR(255),
	"INSTANCEID" NUMBER(19),
	"INSTANCEPATH" VARCHAR(255),
	"INSTANCEUUID" VARCHAR(255),
	"UPDATEDTIME" TIMESTAMP,
	"ZFS" NUMBER(10)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."IMAGE" (
	"TENANTID" NUMBER(15),
	"TENANTUUID" VARCHAR(32),
	"PROJECTID" NUMBER(15),
	"PROJECTUUID" VARCHAR(32),
	"UPLOADER" VARCHAR(32),
	"IMAGEID" NUMBER(15),
	"IMAGEUUID" VARCHAR(32),
	"IMAGENAME" VARCHAR(255),
	"IMAGETAG" VARCHAR(255),
	"IMAGETYPE" VARCHAR(255),
	"DESCRIPTION" VARCHAR(1024),
	"SHARED" VARCHAR(15),
	"STATE" VARCHAR(5),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"UPDATER" VARCHAR(32)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."IMAGELAYERMAPPED" (
	"IMAGEID" NUMBER(15),
	"LAYERID" VARCHAR(64),
	"LAYERORDER" NUMBER(15)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."INNERFILESYSTEMINFO" (
	"INNERFILESYSTEMID" NUMBER,
	"STORAGEUNITID" NUMBER,
	"ROOTPATHNAME" VARCHAR(255),
	"TOTALSIZE" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."INSTANCEINFO" (
	"INSTANCEID" NUMBER,
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"OWNER" VARCHAR(255),
	"INSTANCENAME" VARCHAR(255),
	"INSTANCEDESCRIPTION" VARCHAR(255),
	"INSTANCETAGS" VARCHAR(255),
	"INSTANCETYPE" VARCHAR(255),
	"ENV" VARCHAR(4095),
	"METADATA" VARCHAR(255),
	"NODEID" NUMBER,
	"IMAGEID" NUMBER,
	"HYPERVISORTYPE" VARCHAR(255),
	"SPECID" NUMBER,
	"CPUS" NUMBER,
	"MEMORY" NUMBER,
	"INSTANCESTATUS" VARCHAR(255),
	"RESULT" VARCHAR(255),
	"RESULTMESSAGE" VARCHAR(600),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"AUTOSCALEID" NUMBER,
	"STORAGEGROUPID" NUMBER,
	"STORAGETYPE" NUMBER,
	"INSTANCEGROUPID" NUMBER,
	"INTERNALIP" VARCHAR(255),
	"EXTERNALIP" VARCHAR(255),
	"PUBLICIPID" NUMBER,
	"INSTANCEUUID" VARCHAR(255),
	"TENANTUUID" VARCHAR(255),
	"PROJECTUUID" VARCHAR(255),
	"IMAGEUUID" VARCHAR(255),
	"SPECUUID" VARCHAR(255),
	"AUTOSCALEUUID" VARCHAR(255),
	"STORAGEGROUPUUID" VARCHAR(255),
	"INSTANCEGROUPUUID" VARCHAR(255),
	"ISCDS" NUMBER,
	"AUTOCOUNT" NUMBER,
	"ISDB" NUMBER,
	"ISSERVER" NUMBER,
	"ISSYSTEM" NUMBER,
	"ACTIONID" NUMBER,
	"HOSTID" NUMBER,
	"INSTANCEPMAC" VARCHAR(255),
	"PUBLICIPUUID" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."INSTANCESPECINFO" (
	"SPECID" NUMBER(15),
	"SPECUUID" VARCHAR(25),
	"SPECTYPE" VARCHAR(255),
	"SPECCPU" NUMBER(2),
	"SPECMEMORY" NUMBER(10)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."LAYER" (
	"LAYERID" VARCHAR(64),
	"REFCNT" NUMBER(15)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."NODEIMAGE" (
	"NODEIP" VARCHAR(15),
	"IMAGEID" NUMBER(15),
	"REFCNT" NUMBER(15)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."PACKINFO" (
	"PACKAGEID" NUMBER,
	"PACKAGEUUID" VARCHAR(255),
	"PACKAGEDESC" VARCHAR(255),
	"PACKAGEINFO" VARCHAR(255),
	"PACKAGENAME" VARCHAR(255),
	"PACKAGESOURCE" VARCHAR(10000),
	"PACKAGEUSER" NUMBER(10)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."PHYSICALIMAGE" (
	"IMAGEID" NUMBER(15),
	"IMAGEUUID" VARCHAR(32),
	"PRODUCTNAME" VARCHAR(255),
	"PRODUCTVERSION" VARCHAR(255),
	"IMAGECMD" VARCHAR(1024),
	"IMAGEENV" VARCHAR(4096),
	"IMAGEFROM" VARCHAR(255),
	"SUPPORTOS" VARCHAR(255),
	"DEFAULTCHECK" VARCHAR(2),
	"INSTALLEDPROGRAMS" VARCHAR(4096),
	"ISSNAPSHOT" VARCHAR(2)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."SERVICEINFO" (
	"SVCID" NUMBER,
	"SVCCREATENAME" VARCHAR(255),
	"SVCDELETENAME" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."STORAGEGROUPINFO" (
	"STORAGEGROUPID" NUMBER,
	"TOTALSIZE" NUMBER,
	"TOTALSTORAGENUMBER" NUMBER,
	"USAGE" VARCHAR(255),
	"STORAGETYPE" NUMBER,
	"FREESIZE" NUMBER,
	"TENANTID" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."STORAGENODEINFO" (
	"STORAGENODEID" NUMBER,
	"HOSTID" NUMBER,
	"TOTALCPU" NUMBER(9),
	"TOTALMEMORY" NUMBER(9),
	"TOTALSIZE" NUMBER(9),
	"FREESIZE" NUMBER(9),
	"ACCESSNAME" VARCHAR(255),
	"ACCESSAUTH" VARCHAR(2048),
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."STORAGESERVERGROUPINFO" (
	"STORAGESERVERGROUPID" NUMBER,
	"STORAGEGROUPID" NUMBER,
	"TENANTID" NUMBER,
	"SSVRTYPE" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"PRIVATEPATHNAME" VARCHAR(255)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."STORAGESERVERINFO" (
	"STORAGESERVERID" NUMBER,
	"STORAGEUNITID" NUMBER,
	"STORAGESERVERGROUPID" NUMBER,
	"STORAGESERVERIP" VARCHAR(255),
	"STORAGESERVERPORT" NUMBER,
	"INSTANCEID" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."STORAGEUNITINFO" (
	"STORAGEUNITID" NUMBER,
	"STORAGENODEID" NUMBER,
	"STORAGEGROUPID" NUMBER,
	"TOTALSIZE" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"STORAGETYPE" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX "IMPADMIN"."HOST_PRIM" ON "IMPADMIN"."HOSTINFO" (
	"HOSTID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMAGELAYERMAPPED_COMPLEX_PK" ON "IMPADMIN"."IMAGELAYERMAPPED" (
	"IMAGEID" ASC,
	"LAYERID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMAGE_COMPLEX_PK" ON "IMPADMIN"."IMAGE" (
	"TENANTID" ASC,
	"PROJECTID" ASC,
	"IMAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON1173900572" ON "IMPADMIN"."STORAGENODEINFO" (
	"STORAGENODEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON77100123" ON "IMPADMIN"."FILESTORAGEINFO" (
	"FILESTORAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON90400032" ON "IMPADMIN"."PHYSICALIMAGE" (
	"IMAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON92200033" ON "IMPADMIN"."LAYER" (
	"LAYERID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."NODEIMAGE_COMPLEX_PK" ON "IMPADMIN"."NODEIMAGE" (
	"NODEIP" ASC,
	"IMAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_DBINFO" ON "IMPADMIN"."DBINFO" (
	"DBID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_FILESTORAGEMAPPING" ON "IMPADMIN"."FILESTORAGEMAPPING" (
	"INSTANCEID" ASC,
	"FILESTORAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_INNERFILESYSTEMINFO" ON "IMPADMIN"."INNERFILESYSTEMINFO" (
	"INNERFILESYSTEMID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_SERVICEINFO" ON "IMPADMIN"."SERVICEINFO" (
	"SVCID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_STORAGEGROUPINFO" ON "IMPADMIN"."STORAGEGROUPINFO" (
	"STORAGEGROUPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_STORAGESERVERGROUPINFO" ON "IMPADMIN"."STORAGESERVERGROUPINFO" (
	"STORAGESERVERGROUPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_STORAGESERVERINFO" ON "IMPADMIN"."STORAGESERVERINFO" (
	"STORAGESERVERID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

ALTER TABLE "IMPADMIN"."IMAGELAYERMAPPED" ADD CONSTRAINT "IMAGELAYERMAPPED_COMPLEX_PK"
PRIMARY KEY (
	"IMAGEID",
	"LAYERID"
);

ALTER TABLE "IMPADMIN"."IMAGE" ADD CONSTRAINT "IMAGE_COMPLEX_PK"
PRIMARY KEY (
	"TENANTID",
	"PROJECTID",
	"IMAGEID"
);

ALTER TABLE "IMPADMIN"."STORAGENODEINFO" MODIFY 	"STORAGENODEID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGENODEINFO" MODIFY 	"HOSTID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGENODEINFO" MODIFY 	"TOTALSIZE" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGENODEINFO" MODIFY 	"FREESIZE" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGENODEINFO" ADD 
PRIMARY KEY (
	"STORAGENODEID"
);

ALTER TABLE "IMPADMIN"."FILESTORAGEINFO" MODIFY 	"FILESTORAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."FILESTORAGEINFO" ADD 
PRIMARY KEY (
	"FILESTORAGEID"
);

ALTER TABLE "IMPADMIN"."FILESTORAGEMAPPING" MODIFY 	"INSTANCEID" NOT NULL;

ALTER TABLE "IMPADMIN"."FILESTORAGEMAPPING" MODIFY 	"FILESTORAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."INNERFILESYSTEMINFO" MODIFY 	"INNERFILESYSTEMID" NOT NULL;

ALTER TABLE "IMPADMIN"."INNERFILESYSTEMINFO" MODIFY 	"STORAGEUNITID" NOT NULL;

ALTER TABLE "IMPADMIN"."INNERFILESYSTEMINFO" MODIFY 	"ROOTPATHNAME" NOT NULL;

ALTER TABLE "IMPADMIN"."DBINFO" MODIFY 	"DBID" NOT NULL;

ALTER TABLE "IMPADMIN"."DBINFO" MODIFY 	"STORAGESERVERGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."DBINFO" MODIFY 	"TOTALSIZE" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEGROUPINFO" MODIFY 	"STORAGEGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEGROUPINFO" MODIFY 	"TOTALSIZE" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEGROUPINFO" MODIFY 	"TOTALSTORAGENUMBER" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEGROUPINFO" MODIFY 	"USAGE" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERGROUPINFO" MODIFY 	"STORAGESERVERGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERGROUPINFO" MODIFY 	"STORAGEGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERGROUPINFO" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERINFO" MODIFY 	"STORAGESERVERID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERINFO" MODIFY 	"STORAGEUNITID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERINFO" MODIFY 	"STORAGESERVERGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERINFO" MODIFY 	"STORAGESERVERIP" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERINFO" MODIFY 	"STORAGESERVERPORT" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEUNITINFO" MODIFY 	"STORAGEUNITID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEUNITINFO" MODIFY 	"STORAGENODEID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEUNITINFO" MODIFY 	"STORAGEGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEUNITINFO" MODIFY 	"TOTALSIZE" NOT NULL;

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" ADD 
PRIMARY KEY (
	"IMAGEID"
);

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" MODIFY 	"IMAGEUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" MODIFY 	"PRODUCTNAME" NOT NULL;

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" MODIFY 	"PRODUCTVERSION" NOT NULL;

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" MODIFY 	"IMAGEENV" NOT NULL;

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" MODIFY 	"IMAGEFROM" NOT NULL;

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" MODIFY 	"SUPPORTOS" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGE" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGE" MODIFY 	"TENANTUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGE" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGE" MODIFY 	"IMAGEUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGE" MODIFY 	"IMAGENAME" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGE" MODIFY 	"STATE" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGE" MODIFY 	"CREATEDTIME" NOT NULL;

ALTER TABLE "IMPADMIN"."LAYER" MODIFY 	"LAYERID" NOT NULL;

ALTER TABLE "IMPADMIN"."LAYER" ADD 
PRIMARY KEY (
	"LAYERID"
);

ALTER TABLE "IMPADMIN"."LAYER" MODIFY 	"REFCNT" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGELAYERMAPPED" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGELAYERMAPPED" MODIFY 	"LAYERID" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGELAYERMAPPED" MODIFY 	"LAYERORDER" NOT NULL;

ALTER TABLE "IMPADMIN"."NODEIMAGE" MODIFY 	"NODEIP" NOT NULL;

ALTER TABLE "IMPADMIN"."NODEIMAGE" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."NODEIMAGE" MODIFY 	"REFCNT" NOT NULL;

exit;
