DROP TABLE CSVM_FILE_STALE;
DROP TABLE CSVM_FILE_DIV;
DROP TABLE CSVM_SSVR;
DROP TABLE CSVM_FILE;
DROP TABLE CSVM_DB;
DROP TABLE CSVM_SSVR_GROUP;
DROP TABLE CSVM_STORAGE;
DROP TABLE CSVM_STORAGE_GROUP;

DROP SEQUENCE CSVM_STORAGE_ID_SEQ;
DROP SEQUENCE CSVM_FILE_SEQ;
DROP SEQUENCE CSVM_SSVR_SEQ;

CREATE SEQUENCE CSVM_STORAGE_ID_SEQ;
CREATE SEQUENCE CSVM_FILE_SEQ;
CREATE SEQUENCE CSVM_SSVR_SEQ;

CREATE TABLE CSVM_STORAGE_GROUP
(
    STORAGE_GROUP_UUID      VARCHAR2(8),
    CONSTRAINT CSVM_STORAGE_GROUP_PK PRIMARY KEY(STORAGE_GROUP_UUID)
);

CREATE TABLE CSVM_STORAGE
(
    STORAGE_ID              NUMBER,
    STORAGE_UUID            VARCHAR2(8),
    STORAGE_TYPE            NUMBER,
    TOTAL_SIZE              NUMBER,
    STORAGE_GROUP_UUID      VARCHAR2(8),
    CONSTRAINT CSVM_STORAGE_PK PRIMARY KEY(STORAGE_ID),
    CONSTRAINT CSVM_STORAGE_FK FOREIGN KEY(STORAGE_GROUP_UUID)
        REFERENCES CSVM_STORAGE_GROUP(STORAGE_GROUP_UUID)
);

CREATE TABLE CSVM_SSVR_GROUP
(
    SSVR_GROUP_UUID         VARCHAR2(8),
	STORAGE_GROUP_UUID      VARCHAR2(8),
    CONSTRAINT CSVM_SSVR_GROUP_PK PRIMARY KEY(SSVR_GROUP_UUID),
    CONSTRAINT CSVM_SSVR_GROUP_FK FOREIGN KEY(STORAGE_GROUP_UUID)
        REFERENCES CSVM_STORAGE_GROUP (STORAGE_GROUP_UUID)
);

CREATE TABLE CSVM_DB
(
    DB_UUID                 VARCHAR2(8),
    SSVR_GROUP_UUID         VARCHAR2(8),
    CONSTRAINT CSVM_DB_PK PRIMARY KEY (DB_UUID),
    CONSTRAINT CSVM_DB_FK FOREIGN KEY (SSVR_GROUP_UUID)
        REFERENCES CSVM_SSVR_GROUP (SSVR_GROUP_UUID)
);

CREATE TABLE CSVM_FILE
(
    FILE_ID         NUMBER,
    FILE_NAME       VARCHAR2(256),
    FILE_SIZE       NUMBER,
    DB_UUID         VARCHAR2(8),
    STRIPING_SIZE   NUMBER,
    DIV_COUNT       NUMBER,
    REDUN_COUNT     NUMBER,
    CONSTRAINT CSVM_FILE_PK PRIMARY KEY (FILE_ID),
    CONSTRAINT CSVM_FILE_FK FOREIGN KEY (DB_UUID)
        REFERENCES CSVM_DB (DB_UUID),
    CONSTRAINT CSVM_FILE_UQ UNIQUE (DB_UUID, FILE_NAME)
);

CREATE TABLE CSVM_SSVR
(
    SSVR_ID                 NUMBER,
    SSVR_UUID               VARCHAR2(8),
    STORAGE_ID              NUMBER,
    STORAGE_UUID            VARCHAR2(8),
	TENANT_IP               VARCHAR2(40),
    TENANT_PORT             NUMBER,
    SSVR_GROUP_UUID         VARCHAR2(8),
    INVALID_FLAG            NUMBER(1,0),
    CONSTRAINT CSVM_SSVR_PK PRIMARY KEY (SSVR_ID),
    CONSTRAINT CSVM_SSVR_STORAGE_FK FOREIGN KEY (STORAGE_ID)
        REFERENCES CSVM_STORAGE (STORAGE_ID),
    CONSTRAINT CSVM_SSVR_FK FOREIGN KEY (SSVR_GROUP_UUID)
        REFERENCES CSVM_SSVR_GROUP (SSVR_GROUP_UUID)
);

CREATE TABLE CSVM_FILE_DIV
(
    FILE_ID                 NUMBER,
    DIV_NUM                 NUMBER,
    REDUN_NUM               NUMBER,
    FILE_DIV_SIZE           NUMBER,
    SSVR_ID                 NUMBER,
    FILE_DIV_PATH           VARCHAR2(256),
    CONSTRAINT CSVM_FILE_DIV_PK PRIMARY KEY (FILE_ID, DIV_NUM, REDUN_NUM),
    CONSTRAINT CSVM_FILE_DIV_FK FOREIGN KEY (FILE_ID)
        REFERENCES CSVM_FILE (FILE_ID),
    CONSTRAINT CSVM_FILE_DIV_SSVR_FK FOREIGN KEY (SSVR_ID)
        REFERENCES CSVM_SSVR (SSVR_ID)
);

CREATE TABLE CSVM_FILE_STALE
(
    FILE_ID                 NUMBER,
    REDUN_NUM               NUMBER,
    STRIPENO                NUMBER,
    CONSTRAINT CSVM_FILE_STALE_PK PRIMARY KEY(FILE_ID, REDUN_NUM, STRIPENO),
    CONSTRAINT CSVM_FILE_STALE_FK FOREIGN KEY(FILE_ID)
        REFERENCES CSVM_FILE (FILE_ID)
);


-- Test용 Data
INSERT INTO CSVM_STORAGE_GROUP
    SELECT 'STRGRP00'   -- STORAGE_GROUP UUID
    FROM DUAL;

INSERT INTO CSVM_SSVR_GROUP
    SELECT  'SSVGRP00',  -- SSVR GROUP UUID
            STORAGE_GROUP_UUID
    FROM CSVM_STORAGE_GROUP;

INSERT INTO CSVM_DB
    SELECT  'DBUUID00',                                     -- DB_UUID
            SSVR_GROUP_UUID
    FROM CSVM_SSVR_GROUP;

INSERT INTO CSVM_STORAGE
    SELECT  CSVM_STORAGE_ID_SEQ.NEXTVAL,                -- STORAGE_ID
            'STUUID00',                                 -- STORAGE_UUID
            0,                                          -- STORAGE_TYPE
            1073741824,                                 -- TOTAL_SIZE
            STORAGE_GROUP_UUID                          -- STORAGE_GROU_UUID
    FROM CSVM_STORAGE_GROUP;

INSERT INTO CSVM_SSVR
    SELECT  CSVM_SSVR_SEQ.NEXTVAL,                          -- SSVR_ID
            'SVUUID00',                                     -- SSVR_UUID
            1,                                              -- STORAGE_ID 
            'STUUID00',                                     -- STORAGE_UUID
            '127.0.0.1',                                    -- TENANT_IP
            '33010',                                         -- TENANT_PORT
            'SSVGRP00',                                      -- SSVR_GROUP_UUID
            0                                               -- INVALID_FLAG
    FROM DUAL;

INSERT INTO CSVM_SSVR
    SELECT  CSVM_SSVR_SEQ.NEXTVAL,                          -- SSVR_ID
            'SVUUID01',                                     -- SSVR_UUID
            1,                                              -- STORAGE_ID 
            'STUUID00',                                     -- STORAGE_UUID
            '127.0.0.1',                                    -- TENANT_IP
            '33030',                                         -- TENANT_PORT
            'SSVGRP00',                                      -- SSVR_GROUP_UUID
            0                                               -- INVALID_FLAG
    FROM DUAL;
COMMIT;

exit;
