CREATE TABLE "IMPADMIN"."AGGREGATESTATSENTRY" (
	"ID" NUMBER(19),
	"BYTE_COUNT" NUMBER(19),
	"FLOW_COUNT" NUMBER(19),
	"PACKET_COUNT" NUMBER(19),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(19),
	"DELTA_BYTE_COUNT" NUMBER(19),
	"DELTA_PACKET_COUNT" NUMBER(19)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."FLOWENTRY" (
	"TABLE_NO" NUMBER(10),
	"COOKIE" NUMBER(19),
	"HARD_TIMEOUT" NUMBER(10),
	"IDLE_TIMEOUT" NUMBER(10),
	"INSTRUCTION" VARCHAR(255),
	"MATCH" VARCHAR(255),
	"OUT_GROUP" NUMBER(10),
	"OUT_PORT" NUMBER(10),
	"PRIORITY" NUMBER(10),
	"STATE" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(19),
	"TAG" VARCHAR(500)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."FLOWSTATSENTRY" (
	"ID" NUMBER(19),
	"BYTE_COUNT" NUMBER(19),
	"DURATION_NSEC" NUMBER(19),
	"DURATION_SEC" NUMBER(19),
	"FLAGS" NUMBER(5),
	"HARD_TIMEOUT" NUMBER(10),
	"IDLE_TIMEOUT" NUMBER(10),
	"PACKET_COUNT" NUMBER(19),
	"PRIORITY" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP,
	"TABLE_NO" NUMBER(10),
	"COOKIE" NUMBER(19),
	"DPID" NUMBER(19),
	"DELTA_BYTE_COUNT" NUMBER(19),
	"DELTA_PACKET_COUNT" NUMBER(19)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."GROUPENTRY" (
	"GROUP_ID" NUMBER(10),
	"BUCKETS" VARCHAR(255),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(10),
	"TAG" VARCHAR(500)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."LINKENTRY" (
	"SRC_DPID" NUMBER(10),
	"DST_DPID" NUMBER(10),
	"DST_PORT" NUMBER(10),
	"SRC_PORT" NUMBER(10),
	"COST" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."PORTENTRY" (
	"PORT_NO" NUMBER(10),
	"ADVERTISED" NUMBER(10),
	"CONFIG" NUMBER(10),
	"CURR" NUMBER(10),
	"CURR_SPEED" NUMBER(10),
	"HW_ADDR" BLOB,
	"MAX_SPEED" NUMBER(10),
	"NAME" VARCHAR(255),
	"PEER" NUMBER(10),
	"STATE" NUMBER(10),
	"SUPPORTED" NUMBER(10),
	"UPDATED_TIME" TIMESTAMP,
	"DPID" NUMBER(10)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."PORTSTATSENTRY" (
	"ID" NUMBER(19),
	"COLLISIONS" NUMBER(19),
	"DURATION_NSEC" NUMBER(19),
	"DURATION_SEC" NUMBER(19),
	"RX_BYTES" NUMBER(19),
	"RX_CRC_ERR" NUMBER(19),
	"RX_DROPPED" NUMBER(19),
	"RX_ERRORS" NUMBER(19),
	"RX_FRAME_ERR" NUMBER(19),
	"RX_OVER_ERR" NUMBER(19),
	"RX_PACKETS" NUMBER(19),
	"TX_BYTES" NUMBER(19),
	"TX_DROPPED" NUMBER(19),
	"TX_ERRORS" NUMBER(19),
	"TX_PACKETS" NUMBER(19),
	"UPDATED_TIME" TIMESTAMP,
	"PORT_NO" NUMBER(10),
	"DPID" NUMBER(19),
	"DELTA_TX_BYTES" NUMBER(19),
	"DELTA_TX_PACKETS" NUMBER(19)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "IMPADMIN"."SWITCHENTRY" (
	"DPID" NUMBER(10),
	"AUXILIARY_ID" NUMBER(10),
	"CAPABILITIES" NUMBER(10),
	"DP_DESC" VARCHAR(255),
	"HW_DESC" VARCHAR(255),
	"MFR_DESC" VARCHAR(255),
	"ACTION_MODE" NUMBER(10),
	"N_BUFFERS" NUMBER(10),
	"N_TABLES" NUMBER(10),
	"SERIAL_NUM" VARCHAR(255),
	"SW_DESC" VARCHAR(255),
	"UPDATED_TIME" TIMESTAMP,
	"TYPE" NUMBER(10),
	"IS_ACTIVE" NUMBER(1) DEFAULT 0,
	"IS_CORE" NUMBER(1) DEFAULT 0
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX "IMPADMIN"."ADMIN1_CON152600425" ON "IMPADMIN"."SWITCHENTRY" (
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."ADMIN1_CON153200313" ON "IMPADMIN"."PORTENTRY" (
	"PORT_NO" ASC,
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."ADMIN1_CON158600634" ON "IMPADMIN"."GROUPENTRY" (
	"GROUP_ID" ASC,
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."ADMIN1_CON218600092" ON "IMPADMIN"."LINKENTRY" (
	"SRC_DPID" ASC,
	"DST_DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."ADMIN1_CON475600915" ON "IMPADMIN"."AGGREGATESTATSENTRY" (
	"ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."ADMIN1_CON476700539" ON "IMPADMIN"."PORTSTATSENTRY" (
	"ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."ADMIN1_CON477500565" ON "IMPADMIN"."FLOWENTRY" (
	"TABLE_NO" ASC,
	"COOKIE" ASC,
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."ADMIN1_CON477700738" ON "IMPADMIN"."FLOWSTATSENTRY" (
	"ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

ALTER TABLE "IMPADMIN"."SWITCHENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "IMPADMIN"."SWITCHENTRY" ADD 
PRIMARY KEY (
	"DPID"
);

ALTER TABLE "IMPADMIN"."PORTENTRY" MODIFY 	"PORT_NO" NOT NULL;

ALTER TABLE "IMPADMIN"."PORTENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "IMPADMIN"."PORTENTRY" ADD 
PRIMARY KEY (
	"PORT_NO",
	"DPID"
);

ALTER TABLE "IMPADMIN"."LINKENTRY" MODIFY 	"SRC_DPID" NOT NULL;

ALTER TABLE "IMPADMIN"."LINKENTRY" MODIFY 	"DST_DPID" NOT NULL;

ALTER TABLE "IMPADMIN"."LINKENTRY" ADD 
PRIMARY KEY (
	"SRC_DPID",
	"DST_DPID"
);

ALTER TABLE "IMPADMIN"."FLOWENTRY" MODIFY 	"TABLE_NO" NOT NULL;

ALTER TABLE "IMPADMIN"."FLOWENTRY" MODIFY 	"COOKIE" NOT NULL;

ALTER TABLE "IMPADMIN"."FLOWENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "IMPADMIN"."FLOWENTRY" ADD 
PRIMARY KEY (
	"TABLE_NO",
	"COOKIE",
	"DPID"
);

ALTER TABLE "IMPADMIN"."GROUPENTRY" MODIFY 	"GROUP_ID" NOT NULL;

ALTER TABLE "IMPADMIN"."GROUPENTRY" MODIFY 	"DPID" NOT NULL;

ALTER TABLE "IMPADMIN"."GROUPENTRY" ADD 
PRIMARY KEY (
	"GROUP_ID",
	"DPID"
);

ALTER TABLE "IMPADMIN"."AGGREGATESTATSENTRY" MODIFY 	"ID" NOT NULL;

ALTER TABLE "IMPADMIN"."AGGREGATESTATSENTRY" ADD 
PRIMARY KEY (
	"ID"
);

ALTER TABLE "IMPADMIN"."FLOWSTATSENTRY" MODIFY 	"ID" NOT NULL;

ALTER TABLE "IMPADMIN"."FLOWSTATSENTRY" ADD 
PRIMARY KEY (
	"ID"
);

ALTER TABLE "IMPADMIN"."PORTSTATSENTRY" MODIFY 	"ID" NOT NULL;

ALTER TABLE "IMPADMIN"."PORTSTATSENTRY" ADD 
PRIMARY KEY (
	"ID"
);

ALTER TABLE "IMPADMIN"."FLOWENTRY" ADD CONSTRAINT "FK_FLOWENTRY_DPID"
FOREIGN KEY (
	"DPID"
) REFERENCES "IMPADMIN"."SWITCHENTRY" (
	"DPID"
);

ALTER TABLE "IMPADMIN"."GROUPENTRY" ADD CONSTRAINT "FK_GROUPENTRY_DPID"
FOREIGN KEY (
	"DPID"
) REFERENCES "IMPADMIN"."SWITCHENTRY" (
	"DPID"
);

ALTER TABLE "IMPADMIN"."PORTENTRY" ADD CONSTRAINT "FK_PORTENTRY_DPID"
FOREIGN KEY (
	"DPID"
) REFERENCES "IMPADMIN"."SWITCHENTRY" (
	"DPID"
);

exit;
