---
- name: copy download test shell script
  copy: src=test.sh dest=/{{ user }}/automation/initial/test.sh owner={{ user }} mode=0755

- name: execute shell
  shell: /{{ user }}/automation/initial/test.sh
