---
- name: copy install packages
  copy: src={{ item }}
        dest=/{{ user }}/automation/db_files/
  with_items:
    - "sql_script"
    - "license"

- name: copy make user sql
  copy: src=gen_makeusersql.sh dest=/{{ user }}/automation/db_files owner={{ user }} mode=0755

- name: copy gen setenv
  copy: src=gen_setenv.sh dest=/{{ user }}/automation/db_files owner={{ user }} mode=0755

- name: copy initial iaas db sql
  copy: src=sql_script/create_table.sql dest=/{{ user }}/automation/db_files/sql_script owner={{ user }} mode=0755

- name: copy initial volume manager db sql
  copy: src=sql_script/csvmgr_schema.sql dest=/{{ user }}/automation/db_files/sql_script/ owner={{ user }} mode=0755

- name: copy license.xml
  copy: src=license/license.xml dest=/{{ user }}/automation/db_files/license owner={{ user }} mode=0755
