--- 
- name: if set env in bashrc
  stat:
    path="/root/.bashrc"
  register: ifbashrc

- name: Set env in bashrc
  lineinfile:
    dest: "{{ user_home }}/.bashrc"
    line: "{{ item.line }}"
    backup: yes
    insertafter: "{{ item.after }}"
  with_items:
    - { line: "###################add TIBERO ENV################
			\nexport TB_HOME={{ tb_home }}
			\nexport TB_SID={{ tb_sid }}
			\nexport PATH=$TB_HOME/bin:$TB_HOME/client/bin:$PATH
			\nexport LD_LIBRARY_PATH=$TB_HOME/lib:$TB_HOME/client/lib
			\n####################end TIBERO ENV################
			\n##################################################
			\n####################add CSVMGR ENV################
			\nexport CSVMGR_SID={{ CSVMGR_SID }}
			\nexport CSVMGR_IPADDR={{ CSVMGR_IPADDR }}
			\nexport CSVMGR_PORT={{ CSVMGR_PORT }}
			\nexport CSVMGR_META_DB_NAME={{ CSVMGR_META_DB_NAME }}
			\nexport CSVMGR_META_DB_USER={{ CSVMGR_META_DB_USER }}
			\nexport CSVMGR_META_DB_PWD={{ CSVMGR_META_DB_PWD }}
			\nexport CSVMGR_LOG_DIR=$TB_HOME/instance/$CSVMGR_SID/log
			\nexport CSVMGR_LOG_LEVEL={{ CSVMGR_LOG_LEVEL }}
			\n#################### end CSVMGR ENV################", after: "EOF" }
  when: ifbashrc.stat.exists == True
